const constants = {
    RECEIVE_EVENTS: 'RECEIVE_EVENTS',
    RECEIVE_EVENTS_ERROR: 'RECEIVE_EVENTS_ERROR',

    RECEIVE_USERDATA: 'RECEIVE_USERDATA',
    CLEAR_USERDATA: 'CLEAR_USERDATA',

    EDITOR_SETDATA: 'EDITOR_SETDATA',
    EDITOR_CLEARDATA: 'EDITOR_CLEARDATA',
    EDITOR_SENDDATA: 'EDITOR_SENDDATA',
    EDITOR_SENDDATA_COMPLETE: 'EDITOR_SENDDATACOMPLETE',
    EDITOR_SENDDATA_ERROR: 'EDITOR_SENDDATA_ERROR',
    EDITOR_SENDDATA_SUCCESS: 'EDITOR_SENDDATA_SUCCESS',

    // Local storage keys
    EDITOR_VALUES: 'EDITOR_VALUES'
}

export default constants
